import { useMemo, useState } from 'react';
import type { DiagnosticReport } from '../../types';
import { validateDiagnosticReports, groupHasErrors, groupHasWarnings } from '../../data/validateDiagnosticReports';
import { parseUploadedResults } from '../../data/parseUpload';
import { formatFullDate, pressable } from './ui';
import { exportData } from '../../utils/exportData';
import { loadEnvelopeMeta, saveEnvelopeMeta, type EnvelopeMeta } from '../../data/envelopeMeta';
import { CHATBOT_PROMPT } from '../../data/chatbotPrompt';
import { FileText, CheckCircle2, Sparkles } from 'lucide-react';
import { PageHeader } from './PageHeader';
import { Button, Card, FIELD_INPUT, FileButton, SectionTitle, StatusDot, TABLE, TABLE_TD as td, TABLE_TH as th } from '../primitives';
import { COLOR } from '../../styles/tokens';

const INLINE_BUTTON = { margin: '0 8px' } as const;

export function DiagnosticReportsView({
  sessions,
  onOpenDetail,
  onAddReports,
  onImportFile,
  importError,
  onClear,
}: Readonly<{
  sessions: DiagnosticReport[];
  onOpenDetail: (file: string) => void;
  onAddReports: (groups: ReturnType<typeof parseUploadedResults>) => void;
  onImportFile: (file: File) => Promise<void>;
  importError: string | null;
  onClear: () => void;
}>) {
  const [isExporting, setIsExporting] = useState(false);
  const [copiedPrompt, setCopiedPrompt] = useState(false);
  const [addError, setAddError] = useState<string | null>(null);
  const [isAdding, setIsAdding] = useState(false);
  const [addedCount, setAddedCount] = useState<number | null>(null);
  const [meta, setMeta] = useState<EnvelopeMeta>(() => loadEnvelopeMeta());
  const issues = useMemo(() => validateDiagnosticReports(sessions), [sessions]);

  function updateMeta(patch: Partial<EnvelopeMeta>) {
    setMeta((prev) => {
      const next = { ...prev, ...patch };
      saveEnvelopeMeta(next);
      return next;
    });
  }

  async function handleCopyPrompt() {
    try {
      await navigator.clipboard.writeText(CHATBOT_PROMPT);
      setCopiedPrompt(true);
      setTimeout(() => setCopiedPrompt(false), 2000);
    } catch {
      // clipboard unavailable
    }
  }

  async function handleAddFile(file: File) {
    setAddError(null);
    setAddedCount(null);
    setIsAdding(true);
    // Let the browser paint the "Adding…" state before the synchronous
    // JSON.parse/parseUploadedResults work freezes the main thread.
    await new Promise((r) => setTimeout(r, 50));
    try {
      let json: unknown;
      try {
        json = JSON.parse(await file.text());
      } catch {
        setAddError('Not a valid JSON file.');
        return;
      }
      try {
        const groups = parseUploadedResults(json);
        onAddReports(groups);
        setAddedCount(groups.length);
        setTimeout(() => setAddedCount(null), 4000);
      } catch (e) {
        setAddError(e instanceof Error ? e.message : 'Could not parse the uploaded file.');
      }
    } finally {
      setIsAdding(false);
    }
  }

  const addBlock = (
    <Card style={{ marginBottom: 24, maxWidth: 640 }}>
      <SectionTitle style={{ marginBottom: 12 }}>Add a report</SectionTitle>
      <div style={{ marginBottom: 16 }}>
        <details>
          <summary style={{ color: COLOR.textSecondary, fontSize: 14, cursor: 'pointer', listStyle: 'none' }}>
            1.{' '}
            <Button
              size="xs"
              onClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
                handleCopyPrompt();
              }}
              style={INLINE_BUTTON}
            >
              {copiedPrompt ? '✓ Copied!' : 'Copy'}
            </Button>{' '}
            the chatbot prompt <span style={{ color: COLOR.accent }}>›</span>
          </summary>
          <pre
            style={{
              marginTop: 8,
              padding: 12,
              border: `1px solid ${COLOR.borderSubtle}`,
              borderRadius: 6,
              fontSize: 12,
              lineHeight: 1.5,
              whiteSpace: 'pre-wrap',
              overflowWrap: 'anywhere',
              color: COLOR.textSecondary,
            }}
          >
            {CHATBOT_PROMPT}
          </pre>
        </details>
      </div>
      <div style={{ color: COLOR.textSecondary, fontSize: 14, marginBottom: 16 }}>
        2. Paste into your favourite chatbot and let it parse your Reports from PDFs and Image formats.
      </div>
      <div style={{ color: COLOR.textSecondary, fontSize: 14 }}>
        3.{' '}
        <FileButton size="xs" accept=".json,application/json" disabled={isAdding} onFile={handleAddFile} style={INLINE_BUTTON}>
          {isAdding ? 'Adding…' : 'Add'}
        </FileButton>{' '}
        a new Diagnostic Report pre-generated by your chatbot.
      </div>
      {addError && <div style={{ color: COLOR.statusBadText, fontSize: 14, marginTop: 12 }}>{addError}</div>}
      {addedCount != null && (
        <div style={{ color: COLOR.statusOkText, fontSize: 14, marginTop: 12 }}>
          ✓ Added {addedCount} report{addedCount === 1 ? '' : 's'}.
        </div>
      )}
    </Card>
  );

  return (
    <>
      <PageHeader
        overline="Laboratory Encounter Archive"
        titlePrimary="Diagnostic"
        titleAccent="Reports"
        description={[
          'Uploaded laboratory sessions organized chronologically by draw date and provider.',
          'Inspect raw lab results, verify validation rules, or import new reports.',
        ]}
        pillars={[
          { icon: FileText, line1: 'Chronological', line2: 'report archive' },
          { icon: CheckCircle2, line1: 'Validation & error', line2: 'gating checks' },
          { icon: Sparkles, line1: 'Chatbot prompt', line2: 'JSON extraction' },
        ]}
      />
      {sessions.length > 0 && (
        <details style={{ marginBottom: 24 }}>
          <summary style={{ fontWeight: 600, fontSize: 14, marginBottom: 10, cursor: 'pointer', listStyle: 'none' }}>
            Database details <span style={{ color: COLOR.accent }}>›</span>
          </summary>
          <Card
            style={{
              maxWidth: 480,
              display: 'grid',
              gridTemplateColumns: '90px 1fr',
              columnGap: 14,
              rowGap: 12,
              alignItems: 'center',
              fontSize: 13,
            }}
          >
            <span style={{ color: COLOR.textMuted, textAlign: 'right' }}>Generated at</span>
            <span style={{ color: COLOR.textMuted }}>
              {meta.generatedAt ? new Date(meta.generatedAt).toLocaleString() : '—'}
              <span style={{ color: COLOR.textDisabled, fontSize: 11, marginLeft: 8 }}>updates on each export</span>
            </span>
            <span style={{ color: COLOR.textSecondary, fontWeight: 600, textAlign: 'right' }}>Subject</span>
            <input
              type="text"
              value={meta.subject ?? ''}
              onChange={(e) => updateMeta({ subject: e.currentTarget.value || undefined })}
              style={{ ...FIELD_INPUT, width: '100%', boxSizing: 'border-box' }}
            />
            <span style={{ color: COLOR.textSecondary, fontWeight: 600, textAlign: 'right' }}>Sex</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <select
                value={meta.sex ?? ''}
                onChange={(e) => {
                  const v = e.currentTarget.value;
                  updateMeta({ sex: v === 'female' || v === 'male' ? v : undefined });
                }}
                style={FIELD_INPUT}
              >
                <option value="">(not set)</option>
                <option value="female">female</option>
                <option value="male">male</option>
              </select>
              <span style={{ color: COLOR.textSecondary, fontWeight: 600 }}>Birth year</span>
              <input
                type="number"
                min={1900}
                max={new Date().getFullYear()}
                step={1}
                value={meta.birthYear ?? ''}
                onChange={(e) => {
                  const v = e.currentTarget.value;
                  updateMeta({ birthYear: v === '' ? undefined : Number(v) });
                }}
                style={{ ...FIELD_INPUT, width: 90 }}
              />
            </div>
            <span style={{ color: COLOR.textSecondary, fontWeight: 600, textAlign: 'right', alignSelf: 'start', marginTop: 6 }}>
              Notes
            </span>
            <textarea
              rows={4}
              value={meta.notes ?? ''}
              onChange={(e) => updateMeta({ notes: e.currentTarget.value || undefined })}
              style={{ ...FIELD_INPUT, width: '100%', boxSizing: 'border-box', resize: 'vertical' }}
            />
          </Card>
        </details>
      )}
      {sessions.length > 0 && (
        <div style={{ overflowX: 'auto', margin: '32px 0' }}>
            <table style={TABLE}>
              <thead>
                <tr>
                  <th style={th}></th>
                  <th style={th}>Date</th>
                  <th style={th}>Lab</th>
                  <th style={th}>Observations</th>
                </tr>
              </thead>
              <tbody>
                {/* sessions is already date-descending, as produced by parseUpload/ResultsContext */}
                {sessions.map((group) => (
                  <tr key={group.file} {...pressable(() => onOpenDetail(group.file))} style={{ cursor: 'pointer' }}>
                    <td style={td}>
                      {groupHasErrors(group.file, issues) && <StatusDot tone="bad" title="Errors" />}
                      {!groupHasErrors(group.file, issues) && groupHasWarnings(group.file, issues) && (
                        <StatusDot tone="warn" title="Warnings" />
                      )}
                    </td>
                    <td style={td}>{formatFullDate(group.date)}</td>
                    <td style={td}>{group.place}</td>
                    <td style={td}>{group.itemCount}</td>
                  </tr>
                ))}
              </tbody>
            </table>
        </div>
      )}
      {addBlock}
      {sessions.length > 0 && (
        <Card style={{ marginBottom: 24, maxWidth: 640 }}>
          <div>
            <SectionTitle>Back up your database</SectionTitle>
            <div style={{ color: COLOR.textMuted, fontSize: 13, marginBottom: 12 }}>
              Export it as a JSON file, or import one to replace it.
            </div>
            <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
              <Button
                onClick={async () => {
                  setIsExporting(true);
                  try {
                    const generatedAt = await exportData(sessions, meta);
                    updateMeta({ generatedAt });
                  } finally {
                    setIsExporting(false);
                  }
                }}
              >
                {isExporting ? 'Exporting...' : 'Export JSON'}
              </Button>
              <FileButton accept=".json,application/json" onFile={onImportFile}>
                Import JSON
              </FileButton>
            </div>
            {importError && <div style={{ color: COLOR.statusBadText, fontSize: 14, marginTop: 12 }}>{importError}</div>}
          </div>
          <div style={{ borderTop: `1px solid ${COLOR.borderSubtle}`, marginTop: 16, paddingTop: 16 }}>
            <SectionTitle>Clear local DB</SectionTitle>
            <div style={{ color: COLOR.textMuted, fontSize: 13, marginBottom: 12 }}>
              Removes all loaded reports from this browser. Export first if you want to keep them.
            </div>
            <Button
              variant="danger"
              onClick={() => {
                if (window.confirm('Remove all loaded lab reports?')) onClear();
              }}
            >
              Clear
            </Button>
          </div>
        </Card>
      )}
    </>
  );
}
